"""
Django settings for invest project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# NEED TO SET ENVIRONMENT VARIABLE 'DJANGO_SETTINGS_MODULE' TO this file!!!

# Windows: set DJANGO_SETTINGS_MODULE=invest.production_settings
# Linux: export DJANGO_SETTINGS_MODULE=invest.production_settings
#
# OTHER USEFUL ENVIRONMENT VARIABLES:
# DJANGO_SECRET_KEY_FILE=/etc/keys/invest_secret_key.txt
# DJANGO_DB_CONF_FILE=/etc/mysql/sql_invest.cnf
# DJANGO_STATIC_ROOT=/var/www/invest/static
# DJANGO_MEDIA_ROOT=/var/www/invest/media
# DJANGO_ALLOWED_HOSTS=.example.com,www.example.com
# DJANGO_LOG_LEVEL=INFO
# DJANGO_LOG_FILE=/var/log/invest/django.log

import os
import re
from pathlib import Path
from django.contrib.messages import constants as message_constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variables or a secure file outside the repo to load the secret key
# Example:
# with open('/etc/keys/invest_secret_key.txt') as f:
#     SECRET_KEY = f.read().strip()
_secret_key_file = os.environ.get('DJANGO_SECRET_KEY_FILE')
if _secret_key_file:
    with open(_secret_key_file) as f:
        SECRET_KEY = f.read().strip()
else:
    SECRET_KEY = os.environ.get(
        'DJANGO_SECRET_KEY', 'django-insecure-default-key-for-dev-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = os.environ.get(
    'DJANGO_ALLOWED_HOSTS', '.invest.com').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django_cleanup.apps.CleanupConfig', # Add when you install it
    'users',
    'indicators',
    'scraper',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'invest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTH_USER_MODEL = 'users.User'

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = 'login'

WSGI_APPLICATION = 'invest.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            # Pass the path to your server's database credentials via environment variable
            'read_default_file': os.environ.get('DJANGO_DB_CONF_FILE', '/etc/mysql/sql_invest.cnf'),
        },
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'file': {
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.environ.get('DJANGO_LOG_FILE', BASE_DIR / 'django.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB max file size
            'backupCount': 5,             # Keep 5 backup logs
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': True,
        },
        'django.request': {
            'handlers': ['mail_admins', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-BR'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
# Pass the static root path via environment variable or default to a generic one
STATIC_ROOT = os.environ.get('DJANGO_STATIC_ROOT', '/var/www/invest/static')

MEDIA_URL = '/media/'
# Pass the media root path via environment variable or default to a generic one
MEDIA_ROOT = os.environ.get('DJANGO_MEDIA_ROOT', '/var/www/invest/media')

MESSAGE_TAGS = {
    message_constants.INFO: 'primary',
    message_constants.ERROR: 'danger'
}

SECURE_SSL_REDIRECT = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_HSTS_SECONDS = 60

# ADMINS = [('Samuel', '')]
# MANAGERS = [('Samuel', '')]

IGNORABLE_404_URLS = [
    re.compile(r'^/favicon\.ico$'),
    re.compile(r'^/asset-manifest\.json$'),
    re.compile(r'^/robots\.txt$'),
]
