# Generated by Django 5.1 on 2026-08-22 18:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('reit', 'REIT'), ('fii', 'FII'), ('stock', 'Stock'), ('acao', 'Ação')], max_length=20, unique=True, verbose_name='asset type code')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Asset type',
                'verbose_name_plural': 'Asset types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompositeIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Composite indicator',
                'verbose_name_plural': 'Composite indicators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True, verbose_name='symbol')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='indicators.assettype', verbose_name='asset type')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('key', models.SlugField(max_length=60, verbose_name='key')),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='unit')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('composite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='indicators.compositeindicator', verbose_name='composite indicator')),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetricHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='value')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='timestamp')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='source')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='indicators.metric', verbose_name='metric')),
            ],
            options={
                'verbose_name': 'Metric history',
                'verbose_name_plural': 'Metric history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlisted_by', to='indicators.asset', verbose_name='asset')),
            ],
            options={
                'verbose_name': 'Watchlist entry',
                'verbose_name_plural': 'Watchlist entries',
                'ordering': ['-added_at'],
            },
        ),
    ]
