# Generated by Django 5.1 on 2026-08-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('reit', 'REIT'), ('fii', 'FII'), ('stock', 'Stock'), ('acao', 'Ação')], default='stock', max_length=20, verbose_name='asset type'),
        ),
        migrations.DeleteModel(
            name='AssetType',
        ),
    ]
