# Generated by Django 5.1 on 2026-08-22 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_alter_asset_asset_type_delete_assettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='kind',
            field=models.CharField(choices=[('raw', 'Raw'), ('derived', 'Derived')], default='raw', max_length=20, verbose_name='kind'),
        ),
        migrations.CreateModel(
            name='MetricFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_code', models.CharField(choices=[('shin_v1', 'SHIN indicator (v1)')], max_length=40, verbose_name='formula code')),
                ('expression', models.TextField(verbose_name='expression')),
                ('operands', models.JSONField(blank=True, default=dict, verbose_name='operands')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('metric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formula', to='indicators.metric', verbose_name='metric')),
            ],
            options={
                'verbose_name': 'Metric formula',
                'verbose_name_plural': 'Metric formulas',
                'ordering': ['metric__name'],
            },
        ),
    ]
