# Generated by Django 5.1 on 2026-08-22 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_seed_shin_metric'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metric',
            unique_together={('composite', 'key')},
        ),
        migrations.AddField(
            model_name='compositeindicator',
            name='expression',
            field=models.TextField(blank=True, verbose_name='expression'),
        ),
        migrations.AddField(
            model_name='compositeindicator',
            name='formula_code',
            field=models.CharField(blank=True, choices=[('shin_v1', 'SHIN indicator (v1)')], max_length=40, null=True, verbose_name='formula code'),
        ),
        migrations.AddField(
            model_name='compositeindicator',
            name='operands',
            field=models.JSONField(blank=True, default=dict, verbose_name='operands'),
        ),
        migrations.AddField(
            model_name='metric',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='indicators.asset', verbose_name='asset'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='composite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='indicators.compositeindicator', verbose_name='composite indicator'),
        ),
        migrations.AlterUniqueTogether(
            name='metric',
            unique_together={('asset', 'key'), ('composite', 'key')},
        ),
        migrations.DeleteModel(
            name='MetricFormula',
        ),
    ]
