# Generated by Django 5.1 on 2026-08-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_metric_catalog_per_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='key',
            field=models.SlugField(editable=False, max_length=60, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='name',
            field=models.CharField(choices=[('p_l', 'P/L'), ('p_vp', 'P/VP'), ('dy', 'DY (%)'), ('margem_liquida', 'Margem Líquida (%)'), ('receitas_cagr3', 'CAGR Receitas 3a (%)'), ('receitas_cagr5', 'CAGR Receitas 5a (%)'), ('lucros_cagr3', 'CAGR Lucros 3a (%)'), ('lucros_cagr5', 'CAGR Lucros 5a (%)'), ('shin_indicator', 'SHIN Indicator')], max_length=120, verbose_name='metric name'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='unit',
            field=models.CharField(blank=True, editable=False, max_length=40, verbose_name='unit'),
        ),
    ]
