# Generated by Django 5.2.17 on 2026-10-03 14:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0008_alter_metric_key_alter_metric_name_alter_metric_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metrichistory",
            name="metric",
        ),
        migrations.CreateModel(
            name="MetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="timestamp",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, editable=False, verbose_name="date"
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=255, verbose_name="source"),
                ),
                (
                    "p_l",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="P/L",
                    ),
                ),
                (
                    "p_vp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="P/VP",
                    ),
                ),
                (
                    "dy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="DY (%)",
                    ),
                ),
                (
                    "margem_liquida",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Margem Líquida (%)",
                    ),
                ),
                (
                    "receitas_cagr3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="CAGR Receitas 3a (%)",
                    ),
                ),
                (
                    "receitas_cagr5",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="CAGR Receitas 5a (%)",
                    ),
                ),
                (
                    "lucros_cagr3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="CAGR Lucros 3a (%)",
                    ),
                ),
                (
                    "lucros_cagr5",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="CAGR Lucros 5a (%)",
                    ),
                ),
                (
                    "ffo_cagr3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="CAGR FFO 3a (%)",
                    ),
                ),
                (
                    "ffo_cagr5",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="CAGR FFO 5a (%)",
                    ),
                ),
                (
                    "caixa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Caixa (%)",
                    ),
                ),
                (
                    "dy_cagr3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="CAGR DY 3a (%)",
                    ),
                ),
                (
                    "dy_cagr5",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="CAGR DY 5a (%)",
                    ),
                ),
                (
                    "valor_cagr3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="CAGR Valor 3a (%)",
                    ),
                ),
                (
                    "valor_cagr5",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="CAGR Valor 5a (%)",
                    ),
                ),
                (
                    "shin_indicator",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        editable=False,
                        max_digits=15,
                        null=True,
                        verbose_name="SHIN Indicator",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_snapshots",
                        to="indicators.asset",
                        verbose_name="asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metric snapshot",
                "verbose_name_plural": "Metric snapshots",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.DeleteModel(
            name="Metric",
        ),
        migrations.DeleteModel(
            name="MetricHistory",
        ),
        migrations.AddIndex(
            model_name="metricsnapshot",
            index=models.Index(
                fields=["asset", "-timestamp"], name="asset_snapshot_ts_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="metricsnapshot",
            unique_together={("asset", "date")},
        ),
    ]
